Restore compatibility with < 4.07
ygrek/ocaml-cbor pull request #17
Opened 2021-10-17 12:19 UTC by smorimoto

2021-10-17 12:39 UTC, smorimoto commented
GitHub Actions will not actually be enabled in this repository until after this PR is merged. So, to check the latest build results, see here. You can confirm that everything is just ok: https://github.com/smorimoto/ocaml-cbor/actions/runs/1351401516

2021-11-24 21:21 UTC, ygrek requested changes
Thanks!

2021-11-24 21:21 UTC, ygrek commented on cbor.opam
> +    "--promote-install-files=false"
I didn't see this one before, any particular reason? or is it new best practice? I guess it is related to the subsequent `dune install`?

2021-11-24 21:21 UTC, ygrek commented on dune-project
> +(lang dune 2.9)
can we keep lowest required dune version

2022-02-07 02:56 UTC, ygrek commented
Rebased in bb51892
Thanks

2022-02-07 02:56 UTC, closed without merging