CTAP2 canonical form CBOR encoding parsing
ygrek/ocaml-cbor pull request #19
Opened 2021-11-29 12:43 UTC by reynir

This PR adds a submodule `CBOR.Ctap2_canonical` with a similar signature as `CBOR.Simple` with its own `type t` without `` `Tag`` and a function `to_simple`, but no `to_diagnostic`. What is missing is `encode`.

I took some (mostly) stylistic choices that differ from the existing code - I can adapt it to fit the existing style.

Fixes #18 (parsing only)

The tests cases test both `CBOR.Simple` and `CBOR.Ctap2_canonical` simultaneously. They probably shouldn't.

2022-01-23 16:24 UTC, ygrek requested changes
Thanks and sorry for the late review.
My only concern is changes to the test json, I think we can use test case numbers for ctap2 tests (same as it is done for ignore) from appendix_a and add ctap2-only test cases in separate json

2022-01-23 16:24 UTC, ygrek commented on test/appendix_a.json
> +    "noncanonical": true,
iirc this json was copied straight from the rfc, now this change introduces a (small) diff

2022-01-23 16:24 UTC, ygrek commented on test/appendix_a.json
> +  {
lets rather have new testcases in a separate file

2022-01-26 14:27 UTC, reynir commented
I reverted appendix_a.json and moved the new tests to ctap2.json. I made some changes to the test harness that I'm not too happy about -- it compares the file name of the test json file in order to decide what tests are noncanonical or ignored in appendix_a.json.

Perhaps I should write two separate test programs rather. I will not do it today..

2022-02-06 22:02 UTC, ygrek commented
lgtm, thanks!

2022-02-06 22:02 UTC, merged

2022-02-07 13:29 UTC, ygrek commented
one thing I missed, I think module should be named CTAP2_canonical, do you agree?

2022-02-07 15:34 UTC, ygrek commented
https://github.com/ygrek/ocaml-cbor/commit/480a743fd5a03237bc488a7aec72e102894edee9